pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/TanishqGupta1234/simple-python-pyinstaller-app.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'pytest'  // Run tests (if applicable)
            }
        }
        stage('Build Executable') {
            steps {
                sh 'pyinstaller --onefile main.py'  // Change `main.py` to your Python entry file
            }
        }
    }
}
